### ISSUE TITLE
Data not reset after session

### ISSUE THREAD

**Issue by siddharthsaxena13** [privin/SCM_workshop_FT04#1]
"Show total cash held" is not showing null after the session is over .Upon a subsequent re-login to the maintenance panel in the same session,the cash previously held and already collected persist in display .

**Comment by aditya0711** [comment]
Noted. 
After testing, the same issue was encountered. Im assigning this issue to the Development Team.
Thanks
Aditya

**Comment by privin** [comment]
Hi Samruddhi and Srishti,

Kindly have a look at this issue. 

Thanks,
Priya Vinayak

**Comment by Samruddhijoshi** [comment]
Hi Priya,

This issue has been identified and I request you to create change request.

Thanks,
Samruddhi Joshi

**Comment by privin** [comment]
Hi Manish,

Please raise a Change Request for this issue. 

Thanks,
Priya Vinayak

**Comment by Manish166** [comment]
Hi Priya,

CR (CR0002) has been created for the defect.
Please do the needful.

Thanks,
Manish Singh
[CR0002.docx](![defectafter]%28https://cloud.githubusercontent.com/assets/17695390/18628849/cb34198c-7e94-11e6-81b1-0fe82d3c86c1.jpeg%29
https://github.com/privin/SCM_workshop_FT04/files/479716/CR0002.docx)

![defectbefore](https://cloud.githubusercontent.com/assets/17695390/18628836/bff1a832-7e94-11e6-8142-c248067478ed.jpeg)

**Comment by privin** [comment]
[CR0002.docx](https://github.com/privin/SCM_workshop_FT04/files/479818/CR0002.docx)

Hi Mohan,Samruddhi and Srishti,

Please do the technical analysis for CR (CR0002) and update the CR form attached.

Thanks,
Priya

**Comment by smohankarthik** [comment]
Hi Priya,
Please find the document(CR0002) after the technical analysis.

Regards,
Mohan
[ChangeControlForm_Defect(CR0002).docx](https://github.com/privin/SCM_workshop_FT04/files/479855/ChangeControlForm_Defect.CR0002.docx)

**Comment by privin** [comment]
Hi Manish,

Please find the technical analysis and effort estimation for this CR. Kindly inform me when to proceed with implementation of this CR.

Thanks,
Priya Vinayak

**Comment by Manish166** [comment]
Hi Priya,

As advised by CCB, effort seems to be less than 30 days.
Please go ahead with implementation.

Thanks,
Manish Singh

**Comment by privin** [comment]
[ChangeControlForm_Defect.CR0002.docx](https://github.com/privin/SCM_workshop_FT04/files/479897/ChangeControlForm_Defect.CR0002.docx)
Hi Samruddhi,

Please go ahead with the implementation.
Please find attached the updated document with assignment.

Thanks,
Priya

**Comment by Samruddhijoshi** [comment]
Hi Priya,

I have done the development for CR0002.
Kindly ask the CM team to proceed for merging and assigning to QA team for testing. 

Regards
Samruddhi

**Comment by privin** [comment]
Hi All,

This issue has been tracked with enhancement(To enable accounting check-and-balance work perfectly. #2). It was moved to UAT environment for testing and has been tested successfully by the user. Ready to be moved to production.

Thanks
Priya

**Comment by Manish166** [comment]
Hi Siddarth,

Can we close CR?

Thanks,
Manish Singh,
